Improve documentation with clear installation instructions and detailed development process
JRaviLab/MolEvolvR pull request #56
Opened 2024-10-06 08:33 UTC by teddyCodex

# Description

This PR updates the documentation to provide clearer instructions for setting up a development environment and contributing to the project. Key changes include:

- Added detailed steps to install and load the `usethis`, `devtools`, and `lintr` packages.
- Improved the formatting of the pull request process, making it easier to understand for new contributors.
- Updated various sections for better readability and clarity.

## What kind of change(s) are included?

- [ ] Feature (adds or updates new capabilities)
- [ ] Bug fix (fixes an issue).
- [x] Enhancement (adds functionality, improves documentation).
- [ ] Breaking change (these changes would cause existing functionality to not work as expected).

# Checklist

Please ensure that all boxes are checked before indicating that this pull request is ready for review.

- [x] I have read and followed the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] I have searched for existing content to ensure this is not a duplicate.
- [x] I have performed a self-review of these additions (including spelling, grammar, and related).
- [x] I have added comments to my code to help provide understanding.
- [x] I have added a test which covers the code changes found within this PR.
- [x] I have deleted all non-relevant text in this pull request template.
- [x] **Reviewer assignment**: Tag a relevant team member to review and approve the changes.

2024-10-09 19:40 UTC, the-mayer commented on .github/CONTRIBUTING.md
> +*   Install all development dependencies and then make sure the package passes R CMD check using `devtools`:
As this package includes Bioconductor dependencies, we should probably include instructions on installing [BiocManager](https://www.bioconductor.org/install/) as well. Perhaps after this section, but before `devtools::install_dev_deps()`?

2024-10-09 19:46 UTC, the-mayer requested changes
Thanks for expanding the contribution guidelines. Since we are making changes, I think now might be a good time to add some additional information on getting BiocManager installed as well -- I don't think `devtools::install_dev_deps()` will manage this on it's own. 

@teddyCodex , if you could confirm and modify as appropriate, it would be appreciated!

2024-10-09 21:59 UTC, teddyCodex commented
@the-mayer file updated.

**Side note:** 
Did not find a NEWS.md file in the repo.
Commented out the line referencing it: 
> For user-facing changes, add a bullet to the top of `NEWS.md` (i.e. just below the first header). Follow the style described in <https://style.tidyverse.org/news.html>.

Suggest restoring this line when the file exists to avoid any confusion

2024-10-11 15:04 UTC, the-mayer approved these changes
Good changes @teddyCodex , sending to main

2024-10-11 15:06 UTC, merged