Add error handling to multiple functions
JRaviLab/MolEvolvR pull request #76
Opened 2024-10-08 06:28 UTC by Seyi007

- Implement error handling for mapOption2Process, get_proc_medians, write_proc_medians_table, get_proc_weights, advanced_opts2est_walltime, assign_job_queue, and plot_estimated_walltimes .
- Validate input arguments for each function to ensure they meet expected criteria.
- Use tryCatch blocks to handle errors and warnings gracefully.
- Provide informative error messages and detailed logging where appropriate.
- Ensure functions fail gracefully and provide useful feedback.

Also renamed the functions to the following;
assign_job_queue -> assignJobQueue
make_opts2procs	-> mapOption2Process
map_advanced_opts2procs	-> mapAdvOption2Process
get_proc_medians - calculateProcessRuntime
write_proc_medians_table -> writeProcessRuntime2TSV
write_proc_medians_yml -> writeProcessRuntime2YML
get_proc_weights -> getProcessRuntimeWeights
advanced_opts2est_walltime -> calculateEstimatedWallTimeFromOpts
plot_estimated_walltimes -> plotEstimatedWallTimes

- [x] Feature (adds or updates new capabilities)
- [ ] Bug fix (fixes an issue).
- [x] Enhancement (adds functionality).
- [ ] Breaking change (these changes would cause existing functionality to not work as expected).

# Checklist

- [x] I have read and followed the [CONTRIBUTING.md](CONTRIBUTING.md) guidelines.
- [x] I have searched for existing content to ensure this is not a duplicate.
- [x] I have performed a self-review of these additions (including spelling, grammar, and related).
- [x] I have added comments to my code to help provide understanding.
- [ ] I have added a test which covers the code changes found within this PR.
- [x] I have deleted all non-relevant text in this pull request template.
- [x] **Reviewer assignment**: @jananiravi @

2024-10-10 16:19 UTC, the-mayer requested changes
Thanks for the extra work here @Seyi007! Providing error handling for these functions will definitely be a worthwhile endeavor. I've rebased this PR on the current main branch to pull in some function name changes and .Rd files that have been submitted in other PRs.

I'd like to see a few modifications before I review further:

## `tryCatch()`
In R, the `finally` portion is _always_ evaluated, even if the function generates an error or warning. 

Printing “{function} execution completed.” might introduce confusion among our users, as they may think the function executed successfully even if an error occurred. Additionally, it could be overly verbose. I’d prefer to reserve the finally portion of each tryCatch() for cleanup or custom handler functions rather than messaging.

## `print()` VS `message()`
This is both a stylistic and functional request. Given the choice between `message()` and `print()` I'd prefer that we use `message()`. Essentially, when using message, users may choose to suppress the additional messaging with `suppressWarnings()` or `suppressMessages()` -- `print()` is harder to escape and I'd rather give the user the choice.

## Best option 
Use `rlang::inform()`, `rlang::warn()`, and `rlang::abort()` where appropriate: 
- https://rlang.r-lib.org/reference/abort.html

## Next Steps
Please consider the suggested modifications and submit the PR again for further review. Your efforts are greatly appreciated, and I’m looking forward to seeing the improvements!

2024-10-10 16:51 UTC, jananiravi commented
Thanks for all your work on this @Seyi007. excellent points, @the-mayer! Looking forward to the changes!

2024-10-11 14:26 UTC, Seyi007 commented
Duly noted @the-mayer , I'll get to work on this!

2024-10-17 17:36 UTC, falquaddoomi reviewed
Nice work! Generally, I think having better error reporting will really help things, so thank you for the contribution.

I'm inexperienced at R, so take my comments with a grain of salt. Anyway, I made some suggestions in keeping with what @the-mayer had recommended in a previous comment.

2024-10-18 12:53 UTC, Seyi007 commented on R/blastWrappers.R
> +  })
Yeah, I haven't updated the R/blastWrappers.R file with the suggestions from @the-mayer . I've only updated the first 2 files, and I'm currently working on the said file.

2024-10-18 12:54 UTC, Seyi007 commented on R/assign_job_queue.R
> +suppressPackageStartupMessages(library(rlang))
Duly noted! I'll include it in my next commit.

2024-10-18 13:31 UTC, jananiravi commented on R/assign_job_queue.R
> +suppressPackageStartupMessages(library(rlang))
Also, if you are importing multiple functions from that library, it is better to include it as a dependency in the `imports` list [here](https://github.com/JRaviLab/MolEvolvR/blob/main/DESCRIPTION).

2024-10-18 13:34 UTC, jananiravi commented on R/acc2lin.R
> +      call = sys.call(),
Faisal, what's FAICT?

2024-10-19 17:32 UTC, Seyi007 commented on R/acc2lin.R
> +    )
Duly Noted!

2024-10-20 11:11 UTC, Seyi007 commented
Hi @jananiravi @falquaddoomi, I've implemented all the changes required from the previous review in my latest commit. Could you review this and let me know if I'm missing anything?

2024-10-22 15:42 UTC, falquaddoomi approved these changes
Nice, looks like you got to everything I raised.

2024-10-22 22:22 UTC, jananiravi commented
@falquaddoomi @the-mayer followed the conversation but not the most recent line-by-line edits. Feel free to merge if this looks good. 

Thanks, @Seyi007 !

2024-10-23 05:07 UTC, Seyi007 commented
Yay! Thank you @falquaddoomi @jananiravi

2024-10-30 02:56 UTC, the-mayer approved these changes
Thanks @Seyi007, sending to main!

2024-10-30 02:57 UTC, merged